//this file collects the FIES data processed in the R code and creates teh Food Consumption Score 
	//then saves the combined data for later use 
	clear all      // clears data, value labels, saved results, and programs
	set more off   // prevents output from pausing with "more"

	//Food Insecurty Experience Scale FIES 
		//this data was generated by the R script and uses the international standardizing procedure to intertemporal comparability
		import delimited "${root}/R Code/R Data Landing/household_probs_long.csv", clear
		rename (p_mod) (probability_moderately_insecure)
		
		tempfile w4_5_fies
		save `w4_5_fies'
					
	//Food Consumption Score (FCS) collected via 
	//"SECTION 5C: HOUSEHOLD AGGREGATE FOOD CONSUMPTION" (wave 5) "SECTION 10C: AGGREGATE FOOD CONSUMPTION" (wave 4)
	//in post harvest houeshold survey
		//wave 5
			//last section of food consumption is exactly what we need presubably by design
			//found in section 5c of post harvest household survey
			use "${root}/Source Data/Nigeria GHS Wave 5/Raw DTA files/sect5c_harvestw5.dta", clear
			
			drop if inlist(item_cd,6,11,12) //not core categories spices and beverages
			
			//weighting different answers using standard equation:
			// Food Group       Weight
			// Main staples     2
			// Pulses           3
			// Vegetables       1
			// Fruit            1
			// Meat/Fish        4
			// Milk             4
			// Sugar            0.5
			// Oil              0.5

			collapse (max) s5cq8, by(hhid item_cd)
			gen weight = 2
			replace weight = 3 if item_cd==3
			replace weight = 1 if item_cd==4
			replace weight = 1 if item_cd==7
			replace weight = 4 if item_cd==5
			replace weight = 4 if item_cd==8
			replace weight = 0.5 if item_cd==10
			replace weight = 0.5 if item_cd==9
			
			//generating each part of the score w/ weights
			gen weighted_consumption = s5cq8*weight
			
			//generating household scores
			collapse (sum) weighted_consumption, by(hhid)
			rename weighted_consumption FCS_index
			gen wave = 5
			
			//temp file for merging later
			tempfile w5_fcs
			save `w5_fcs'
			
		//wave 4
			//last section of food consumption is exactly what we need presubably by design
			use "${root}/Source Data/Nigeria GHS Wave 4/Raw DTA files/sect10c_harvestw4.dta", clear
			
			drop if inlist(item_cd,6,11) //not core categories spices and beverages
			
			//weighting different answers using standard equation:
			// Food Group       Weight
			// Main staples     2
			// Pulses           3
			// Vegetables       1
			// Fruit            1
			// Meat/Fish        4
			// Milk             4
			// Sugar            0.5
			// Oil              0.5
			
			collapse (max) s10cq8, by(hhid item_cd)
			gen weight = 2
			replace weight = 3 if item_cd==3
			replace weight = 1 if item_cd==4
			replace weight = 1 if item_cd==7
			replace weight = 4 if item_cd==5
			replace weight = 4 if item_cd==8
			replace weight = 0.5 if item_cd==10
			replace weight = 0.5 if item_cd==9
			
			//generating each part of the score w/ weights
			gen weighted_consumption = s10cq8*weight
			
			//generating household scores
			collapse (sum) weighted_consumption, by(hhid)
			
			rename weighted_consumption FCS_index			
			gen wave = 4
			append using `w5_fcs'
			
			tempfile w4_5_FCS
			save `w4_5_FCS'

	//pulling data
		merge 1:1 hhid wave using `w4_5_fies', gen(m1)
			keep if m1==3
			drop m1 
			
		save "${root}/Stata Code/Stata Data Landing/Master_Food_Security_indexs_both_waves_long.dta",replace